export const EXECUTION_LAW = {
  version: '1.0.0',
  status: 'mandatory',
  doctrine: {
    statement: 'Execute only what is explicitly specified. Do not infer. Do not embellish. Do not optimize beyond spec.',
    mandatorySequence: [
      'read',
      'understand',
      'assess',
      'dependency_check',
      'impact_analysis',
      'implementation_plan',
      'controlled_build',
      'compile',
      'test',
      'audit',
      'regression_scan',
      'performance_scan',
      'standards_validation',
      'completion_report',
      'await_next_instruction',
    ],
  },
  prohibitedBehaviors: [
    'speculative_building',
    'assumption_based_architecture',
    'replacing_defined_stack',
    'adding_unapproved_dependencies',
    'changing_design_language',
    'renaming_files_without_instruction',
    'moving_routes_without_instruction',
    'altering_data_contracts_without_instruction',
    'deleting_existing_logic_without_instruction',
    'silent_refactors',
    'silent_schema_changes',
    'introducing_placeholder_code',
    'introducing_mock_quality_ui',
    'partial_completion',
    'hidden_breaking_changes',
    'skipping_tests',
    'skipping_build_compile',
    'skipping_audit',
    'skipping_regression_checks',
  ],
  buildDiscipline: {
    read: [
      'read_full_spec',
      'read_related_modules',
      'read_existing_architecture',
      'understand_constraints',
      'understand_ui_law',
      'understand_permission_law',
      'understand_audit_law',
    ],
    assess: [
      'identify_dependencies',
      'identify_route_impacts',
      'identify_component_impacts',
      'identify_api_impacts',
      'identify_state_impacts',
      'identify_design_impacts',
      'identify_security_impacts',
      'identify_regression_risk',
    ],
    plan: [
      'define_precise_build_steps',
      'define_order_of_execution',
      'define_validation_checkpoints',
      'define_rollback_checkpoint',
      'define_acceptance_criteria',
    ],
    build: {
      mode: 'surgical',
      rules: [
        'smallest_safe_changeset',
        'preserve_existing_contracts',
        'preserve_visual_consistency',
        'preserve_theme_consistency',
        'preserve_motion_consistency',
        'preserve_type_safety',
        'preserve_accessibility',
        'preserve_security_model',
      ],
    },
    compile: {
      mandatory: true,
      mustPass: [
        'lint',
        'typecheck',
        'unit_test',
        'integration_test',
        'build_compile',
      ],
    },
    audit: {
      mandatory: true,
      verify: [
        'routes',
        'rendering',
        'responsiveness',
        'permissions',
        'events',
        'notifications',
        'logs',
        'security',
        'accessibility',
        'visual_quality',
        'data_integrity',
      ],
    },
    regressionScan: {
      mandatory: true,
      verify: [
        'no_route_breakage',
        'no_component_breakage',
        'no_state_breakage',
        'no_style_breakage',
        'no_theme_breakage',
        'no_api_breakage',
        'no_schema_breakage',
        'no_auth_breakage',
        'no_permissions_breakage',
      ],
    },
  },
  completionReport: {
    mandatorySections: [
      'objective',
      'files_created',
      'files_modified',
      'dependencies_added',
      'routes_added',
      'components_added',
      'contracts_added',
      'tests_run',
      'build_status',
      'audit_status',
      'regression_status',
      'unresolved_items',
      'recommendations',
      'ready_for_next_instruction',
    ],
  },
} as const;

export type ExecutionMode = 'strict_controlled_execution';
export type BuildMode = 'surgical';
export type MandatoryCheck = typeof EXECUTION_LAW.buildDiscipline.compile.mustPass[number];
export type AuditCheck = typeof EXECUTION_LAW.buildDiscipline.audit.verify[number];
export type RegressionCheck = typeof EXECUTION_LAW.buildDiscipline.regressionScan.verify[number];